"""new chat architecture

Revision ID: 5a07004ad707
Revises: 9be09d87a090
Create Date: 2026-05-10 19:24:48.417306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a07004ad707'
down_revision: Union[str, None] = '9be09d87a090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_keys',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_aes_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('chat_members',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='membertype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_index('idx_chat_members_user_id', 'chat_members', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.drop_table('user_aes_keys')
    op.add_column('chats', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('name', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('is_group', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('chats_receiver_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_sender_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chats', 'sender_id')
    op.drop_column('chats', 'content')
    op.drop_column('chats', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_sender_id_fkey', 'chats', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chats_receiver_id_fkey', 'chats', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'is_group')
    op.drop_column('chats', 'description')
    op.drop_column('chats', 'name')
    op.drop_column('chats', 'owner_id')
    op.create_table('user_aes_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_aes_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('receiver_aes_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='user_aes_keys_receiver_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='user_aes_keys_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_aes_keys_pkey'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uix_sender_receiver')
    )
    op.drop_index('idx_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_chat_members_user_id', table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_table('chat_keys')
    # ### end Alembic commands ###
